<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerA1c0bux\appProdProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerA1c0bux/appProdProjectContainer.php') {
    touch(__DIR__.'/ContainerA1c0bux.legacy');

    return;
}

if (!\class_exists(appProdProjectContainer::class, false)) {
    \class_alias(\ContainerA1c0bux\appProdProjectContainer::class, appProdProjectContainer::class, false);
}

return new \ContainerA1c0bux\appProdProjectContainer([
    'container.build_hash' => 'A1c0bux',
    'container.build_id' => '6138d324',
    'container.build_time' => 1706720744,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerA1c0bux');
