<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerJmiqgs9\appDevDebugProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerJmiqgs9/appDevDebugProjectContainer.php') {
    touch(__DIR__.'/ContainerJmiqgs9.legacy');

    return;
}

if (!\class_exists(appDevDebugProjectContainer::class, false)) {
    \class_alias(\ContainerJmiqgs9\appDevDebugProjectContainer::class, appDevDebugProjectContainer::class, false);
}

return new \ContainerJmiqgs9\appDevDebugProjectContainer([
    'container.build_hash' => 'Jmiqgs9',
    'container.build_id' => '0ac5292a',
    'container.build_time' => 1706724315,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerJmiqgs9');
